apiVersion: 1

datasources:
  - name: SmartCrop API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://iot-flask-api:5000
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
